FROM grafana/alloy:latest
RUN mkdir -p /var/lib/alloy/data && chown -R 473:473 /var/lib/alloy/data
USER 473
# Install a tiny fetch tool for healthcheck; remove package cache
# Note Alloy image is not designed to run on Alpine Linux 
# Debian based image: use apt-get
RUN apt-get update && apt-get install -y wget
# run as alloy's non root (nobody:nogroup)
USER 65534:65534
